<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UserSecretsId>61ea3258-ff2f-47bc-98ac-f0e942e0f6e4</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Properties\**" />
    <EmbeddedResource Remove="Properties\**" />
    <None Remove="Properties\**" />
    <Page Remove="Properties\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\Images\Login\login-background.jpeg" />
    <None Remove="Assets\Images\Login\login-logo.png" />
    <None Remove="Assets\Images\maze-white.png" />
    <None Remove="Assets\Images\TodoList\geometric-seamless-pattern_97458.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Images\maze-white.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Humanizer.Core.ru" />
    <PackageReference Include="LoadingSpinner.WPF" />
    <PackageReference Include="MahApps.Metro.IconPacks.FontAwesome" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" />
  
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TodoListApp.ApiClient\TodoListApp.ApiClient.csproj" />
    <ProjectReference Include="..\TodoListApp.Core\TodoListApp.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Images\Login\login-background.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Login\login-logo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\TodoList\geometric-seamless-pattern_97458.jpg" />
  </ItemGroup>

</Project>
