name: todo

services:
  api:
    image: painven/todo_api:latest
    container_name: todo_api
    restart: unless-stopped
    env_file: ".env.api"
    ports:
      - "8090:80"
    environment:
      ASPNETCORE_URLS: http://+:80
    networks:
    - todo_network

  db:
    image: postgres@sha256:10d6e725f9b2f5531617d93164f4fc85b1739e04cab62cbfbfb81ccd866513b8
    container_name: todo_database
    restart: always
    env_file: ".env.db"
    volumes:
      - todolist_pgdata:/var/lib/postgresql/data # Persists data in a named volume
    networks:
      - todo_network

  webui:
    image: painven/todo_web:latest
    container_name: todo_web
    restart: unless-stopped
    env_file: ".env.web"
    ports:
      - "8070:80"
    networks:
    - todo_network
    environment:
      ASPNETCORE_URLS: http://+:80
      ApiConfiguration__Host: "http://api:80"
    depends_on:
      - api

networks:  
  todo_network:
    name: todo_network
    external: true

volumes:
  todolist_pgdata:
    external: true