<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UserSecretsId>61ea3258-ff2f-47bc-98ac-f0e942e0f6e4</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Images\Budget\budget-background-texture.jpg" />
    <None Remove="Assets\Images\Login\login-background.jpeg" />
    <None Remove="Assets\Images\Login\login-logo.png" />
    <None Remove="Assets\Images\ReadList\book-placeholder.png" />
    <None Remove="Assets\Images\ReadList\texture-1.png" />
    <None Remove="Assets\Images\ReadList\texture-2.jpg" />
    <None Remove="Assets\Images\ShoppingList\shopping-background.jpg" />
    <None Remove="Assets\Images\TodoList\geometric-seamless-pattern_97458.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="11.0.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="11.0.0" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Dapper" Version="2.0.123" />
    <PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
    <PackageReference Include="LoadingSpinner.WPF" Version="1.0.0" />
    <PackageReference Include="MahApps.Metro.IconPacks.FontAwesome" Version="4.11.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="6.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="6.0.0" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.39" />
    <PackageReference Include="MySql.Data" Version="8.0.29" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="7.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Images\Budget\budget-background-texture.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Login\login-background.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Login\login-logo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\ReadList\book-placeholder.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\ReadList\texture-1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\ReadList\texture-2.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\ShoppingList\shopping-background.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\TodoList\geometric-seamless-pattern_97458.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\Controls\TodoListTab\TodoListTabCardView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Views\Controls\TodoListTab\TodoListTabCardView.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

</Project>
