<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>8b9fcd1e-24c4-45e8-9ae6-83138de090d1</UserSecretsId>
	<ContainerRepository>painven/todo_web</ContainerRepository>
	<ContainerImageName>painven/todo_web</ContainerImageName>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TodoListApp.ApiClient\TodoListApp.ApiClient.csproj" />
    <ProjectReference Include="..\TodoListApp.Core\TodoListApp.Core.csproj" />
  </ItemGroup>

</Project>
