<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>806c87b5-e791-4389-a390-7dc59b2d43f0</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	<ContainerRepository>painven/todo_api</ContainerRepository>
	<ContainerImageName>painven/todo_api</ContainerImageName>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TodoListApp.Core\TodoListApp.Core.csproj" />
  </ItemGroup>
	<ItemGroup>
		<PackageReference Include="Dapper"  />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions"  />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets"  />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"  />
		<PackageReference Include="Painven.TelegramNotificator"  />
		<PackageReference Include="Scrutor"  />
	</ItemGroup>

</Project>
